name = "measurestack-leadgen"
pages_build_output_dir = "./public"
compatibility_date = "2026-08-05"
compatibility_flags = ["nodejs_compat"]

[vars]
STRIPE_GROWTH_PRICE_ID = "price_1U172MABkQitbRJZFiwrihDp"
STRIPE_SCALE_PRICE_ID = "price_1U172vABkQitbRJZs8QGyEPN"
IP_ANONYMIZATION_MODE = "anonymize_strict"
JS_CLIENT_ID_MODE = "first_party_uuid"

[[d1_databases]]
binding = "DB"
database_name = "measurestack-identity"
database_id = "96ebc52b-126a-4c31-8441-f412faa7ae35"
